apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_URL #ME_CONFIG_MONGODB_SERVER
          value: "mongodb://droadmin:droadmin123@mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "dro-user"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "admin@2022"
        image: mongo-express:latest
        imagePullPolicy: Always
        name: mongo-express
        ports:
        - containerPort: 8081
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express 
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
  selector:
    app: mongo-express
  type: LoadBalancer

